// nuxt/components/RichTextSketch.vue
<template>
  <div class="rich-text" v-html="copyHtml" />
</template>

<script setup>
import { toHTML } from '@portabletext/to-html';

// Props
const props = defineProps({
  copy: {
    type: Array,
    required: false
  }
});

const customCopy = {
  marks: {
    'sketch-underline': ({ children }) => {
      return `<span class='sketch-underline'>${children}</span>`
    },
    'sketch-circle': ({ children }) => {
      return `<span class='sketch-circle'>${children}</span>`;
    },
    'sketch-bold': ({ children }) => `<strong class='sketch-bold'>${children}</strong>`,
    'sketch-note': ({ children }) => `<span class='sketch-note'>${children}</span>`
  },
  list: {
    bullet: ({ children }) => `<ul>${children}</ul>`,
    number: ({ children }) => `<ol>${children}</ol>`,
  }
}
const copyHtml = toHTML(props.copy, {components: customCopy});
</script>

<style lang="scss">
.rich-text {
  line-height: 2em;

  .sketch-underline {
    border-bottom: 1.5px solid $flesh;
  }

  .sketch-circle {
    border: 1.5px solid $flesh;
    border-radius: 50%;
  }

  .sketch-bold {
    color: $flesh;
    font-weight: 900;
    text-transform: uppercase;
  }

  .sketch-note {
    color: $flesh;
    text-transform: none;
    font-family: fantasy, cursive, sans-serif;
  }
}
</style>

// sanity/schemas/shared/rich-text-sketch.jsx
import { defineType } from 'sanity';
import { CustomTextarea } from '../../components/custom-textarea';
import { UnderlineIcon, EditIcon, BoldIcon, ActivityIcon } from '@sanity/icons';
// Sanity Icon Set: https://icons.sanity.build/all

export default defineType({
  name: 'richTextSketch',
  title: 'Rich Text Sketch',
  type: 'array',
  components: {
    input: CustomTextarea,
  },
  of: [{
    type: 'block',
    styles: [],
    lists: [],
    marks: {
      decorators: [
        {
          title: 'Underline',
          value: 'sketch-underline',
          icon: UnderlineIcon,
          component: ({ children }) =>
            <span style={{ borderBottom: '1.5px solid #e26844' }}>{children}</span>
        },
        {
          title: 'Circle',
          value: 'sketch-circle',
          icon: EditIcon,
          component: ({ children }) =>
            <span style={{ border: '1.5px solid #e26844', borderRadius: '50%' }}>{children}</span>
        },
        {
          title: 'Bold',
          value: 'sketch-bold',
          icon: BoldIcon,
          component: ({ children }) =>
            <span style={{ display: 'inline-block', color: '#e26844', fontWeight: 'bold', textTransform: 'uppercase' }}>{children}</span>
        },
        {
          title: 'Sketch',
          value: 'sketch-note',
          icon: ActivityIcon,
          component: ({ children }) =>
            <span style={{ display: 'inline-block', color: '#e26844', fontFamily: 'fantasy, cursive, sans-serif', fontWeight: 'bold' }}>{children}</span>
        }
      ],
      annotations: []
    }
  }]
});
